### ISSUE TITLE
Another iOS crash

### ISSUE THREAD

**Issue by SudoPlz** [amplitude/Amplitude-iOS#156] opened 2017-11-08 18:25 UTC
Here's the stack trace:

```
SIGABRT
    /usr/lib/system/libsystem_kernel.dylib ___pthread_kill
    /usr/lib/system/libsystem_pthread.dylib _pthread_kill$VARIANT$mp
    /usr/lib/system/libsystem_c.dylib _abort
    /usr/lib/system/libsystem_malloc.dylib _szone_error
    /usr/lib/system/libsystem_malloc.dylib _free_list_checksum_botch.330
    /usr/lib/system/libsystem_malloc.dylib _tiny_malloc_from_free_list
    /usr/lib/system/libsystem_malloc.dylib _szone_malloc_should_clear
    /usr/lib/system/libsystem_malloc.dylib _malloc_zone_malloc
    /usr/lib/libsqlite3.dylib _sqlite3_config
    /usr/lib/libsqlite3.dylib _sqlite3_vfs_find
    /usr/lib/libsqlite3.dylib _sqlite3_overload_function
    /usr/lib/libsqlite3.dylib _sqlite3_overload_function
    /usr/lib/libsqlite3.dylib _sqlite3_overload_function
    /usr/lib/libsqlite3.dylib _sqlite3_rekey
    /usr/lib/libsqlite3.dylib _sqlite3_open_v2
    Pods/Amplitude-iOS/Amplitude/AMPDatabaseHelper.m:188:13 __51-[AMPDatabaseHelper inDatabaseWithStatement:block:]_block_invoke
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_queue_barrier_sync_invoke_and_complete
    Pods/Amplitude-iOS/Amplitude/AMPDatabaseHelper.m:187:5 -[AMPDatabaseHelper inDatabaseWithStatement:block:]
    Pods/Amplitude-iOS/Amplitude/AMPDatabaseHelper.m:493:5 -[AMPDatabaseHelper getValueFromTable:key:]
    Pods/Amplitude-iOS/Amplitude/Amplitude.m:859:38 -[Amplitude getNextSequenceNumber]
    Pods/Amplitude-iOS/Amplitude/Amplitude.m:681:50 -[Amplitude annotateEvent:]
    Pods/Amplitude-iOS/Amplitude/Amplitude.m:612:9 __117-[Amplitude logEvent:withEventProperties:withApiProperties:withUserProperties:withGroups:withTimestamp:outOfSession:]_block_invoke
    Pods/Amplitude-iOS/Amplitude/Amplitude.m:511:9 -[Amplitude runOnBackgroundQueue:]
    Pods/Amplitude-iOS/Amplitude/Amplitude.m:581:5 -[Amplitude logEvent:withEventProperties:withApiProperties:withUserProperties:withGroups:withTimestamp:outOfSession:]
    Pods/Amplitude-iOS/Amplitude/Amplitude.m:1177:5 -[Amplitude sendSessionEvent:]
    Pods/Amplitude-iOS/Amplitude/Amplitude.m:1159:9 -[Amplitude startNewSession:]
    Pods/Amplitude-iOS/Amplitude/Amplitude.m:1126:13 -[Amplitude startOrContinueSession:]
    Pods/Amplitude-iOS/Amplitude/Amplitude.m:1076:9 __28-[Amplitude enterForeground]_block_invoke
    Frameworks/Foundation.framework/Foundation ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
    Frameworks/Foundation.framework/Foundation -[NSBlockOperation main]
    Frameworks/Foundation.framework/Foundation -[__NSOperationInternal _start:]
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_block_invoke_direct$VARIANT$mp
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_block_invoke_direct$VARIANT$mp
    /usr/lib/system/libdispatch.dylib _dispatch_block_perform$VARIANT$mp
    Frameworks/Foundation.framework/Foundation ___NSOQSchedule_f
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_continuation_pop$VARIANT$mp
    /usr/lib/system/libdispatch.dylib __dispatch_async_redirect_invoke$VARIANT$mp
    /usr/lib/system/libdispatch.dylib __dispatch_root_queue_drain
    /usr/lib/system/libdispatch.dylib __dispatch_worker_thread3
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
```

Amplitude-iOS 3.14.1

**Comment by djih** [comment] 2017-11-09 20:26
Thanks for reporting @SudoPlz . Are you able to reproduce this? It looks like a malloc error when trying to open the sqlite3 database, which is really weird.

**Comment by SudoPlz** [comment] 2017-11-09 23:32
Hey @djih. I received this on our bug tracker today, so unfortunately I don't have a good way to reproduce this.

I do have the operations taking place at each thread though, but I don't think that will help a lot to be honest.

What can I do to help you fix this?

**Comment by numist** [comment] 2018-09-24 20:58
This stack is consistent with heap corruption in the process. What builds of iOS reported this crash?

**Comment by haoliu-amp** [comment] 2019-11-21 00:56
I'm closing this since this ticket is too old. Pls reopen it if you experience again.

**Closed by haoliu-amp** 2019-11-21 00:56 UTC
