### ISSUE TITLE
[iOS 13] Crash within makeEventUploadPostRequest

### ISSUE THREAD

**Issue by rob-keepsafe** [amplitude/Amplitude-iOS#208] opened 2019-10-02 19:45 UTC
Hi there again 👋 

We're seeing a new set of crashes in both iOS 13.0.x and 13.1.x (the gift of crashes that Apple keeps giving). 

Oddly enough, the crash points to `NSString *apiVersionString = [[NSNumber numberWithInt:kAMPApiVersion] stringValue];` here: https://github.com/amplitude/Amplitude-iOS/blob/master/Amplitude/Amplitude.m#L1000

This might be a crash internal to iOS 13 itself, but wanted to at least make you all aware of it.

<img width="1129" alt="Screen Shot 2019-10-02 at 3 28 09 PM" src="https://user-images.githubusercontent.com/30269720/66075951-a9b35480-e52a-11e9-9717-e09d3aa1ff5b.png">

And Xcode did have a set of these for iOS 13.0.x as well

<img width="243" alt="Screen Shot 2019-10-02 at 3 38 43 PM" src="https://user-images.githubusercontent.com/30269720/66075996-cbacd700-e52a-11e9-91fb-1001080965a3.png">

**Comment by haoliu-amp** [comment] 2019-11-21 21:08
Thanks for heads up @rob-keepsafe . I think it was caused by iOS 13, does it crash every time when this line executes?

**Comment by rob-keepsafe** [comment] 2019-11-22 03:30
@haoliu-amp Yes. I've just set the version manually for now as a string and it doesn't crash (rather than doing the number -> string dance)

**Comment by haoliu-amp** [comment] 2019-12-25 06:19
@rob-keepsafe I tried to reproduce it but it works fine under iOS 13. Are you able to get a solid repro for this issue?

**Comment by rob-keepsafe** [comment] 2019-12-27 03:49
Unfortunately no solid repro. We didn't have a choice but to work around it and move on since we were seeing these (and many other 3rd party iOS 13) crashes in production but weren't reproducing them in QA sessions. Apple may have fixed this by now, but we use a forked version of Amplitude anyways so we'll likely leave this fix in place.

**Comment by haoliu-amp** [comment] 2019-12-27 19:29
Thank you for so much details. I will close this ticket for now, but welcome to reach out to us for help!

**Closed by haoliu-amp** 2019-12-27 19:29 UTC
Labels: ios 13
